### ISSUE TITLE
Generating config file displays misleading  error message

### ISSUE THREAD

**Issue by bmuenzenmeyer** [go-vela/cli#21]
Trying out vela, excited for this. Thanks! In the spirit of giving constructive feedback, I wanted to open this. There is a confusing message displayed upon initial creation of a config file

### To reproduce

I used https://go-vela.github.io/docs/usage/reference/cli/authentication/#configuration-file to first generate my token.

I then used the following command to generate the config file (token and url redacted):

### Actual Result

```
vela generate config --addr <<URL_REDACTED>> --token <<TOKEN_REDACTED>>
time="2019-11-15T10:36:04-06:00" level=warning msg="Unable to find config file @ C:\\Users\\<<USER_REDACTED>>/.vela/config.yml"
```

The `msg` text made me concerned this command failed. But inspecting the path mentioned revealed the file was created successfully.

### Expected Result

The command succeeds without a message, or with explicit success messaging

### Wild Speculation

Perhaps this `msg` comes earlier in the process, during some initialization step for all vela commands that looks for this config file? In this case, it's a bit of a one-time 🐔 and 🥚 problem

**Comment by jbrockopp** [comment]
Thanks for providing feedback! 🎉 

We actually had some talks about this on our side, and one of the things we discussed was adding a message to that output 👍 

Would this PR help satisfy your use-case?

https://github.com/go-vela/cli/pull/19

**Comment by bmuenzenmeyer** [comment]
you bet - sorry I missed that!

**Comment by jbrockopp** [comment]
@bmuenzenmeyer awesome 🎉 Happy to hear it!

Also, no worries! We just opened the PR ~ an hour or so ago 👍

**Comment by jbrockopp** [comment]
@bmuenzenmeyer we are going to close this as we believe this is resolved!

We have cut a new release ([`v0.1.6`](https://github.com/go-vela/cli/releases/tag/v0.1.6)) that contains the PR discussed above!

Please feel free to re-open this issue and/or open a new one if you this this is closed incorrectly 👍
