### ISSUE TITLE
Add prompt for the value of a secret to avoid secrets in command line history

### ISSUE THREAD

**Issue by ahatzz11** [go-vela/cli#23]
Right now the CLI requires the value of a secret to be in the command being ran, e.g. 

```
$ vela add secret --type org --org github --repo '*' --name docker_password --value "password"
```

This means that the secret value might end up in a history file somewhere. It would be cool if vela had a separate prompt for the value of a secret. 

```
$ vela add secret --type org --org github --repo '*' --name docker_password
enter secret value: 
```

A verification of the secret could be added by prompting twice, similar to how `gopass insert` works.

vela already does this when doing the initial login:

![image](https://user-images.githubusercontent.com/6256032/69074840-c4b42800-09f5-11ea-9444-c1e67928f2d5.png)

**Comment by jbrockopp** [comment]
Looks like this was also opened internally 👍 

But, you can add secrets from a file so you don't directly have to store them in your history:

https://go-vela.github.io/docs/usage/reference/cli/secret/add/#secrets-from-a-file

FYI: there are other ways to ensure that the command history isn't saved 🎉 

https://stackoverflow.com/questions/6475524/how-do-i-prevent-commands-from-showing-up-in-bash-history

https://unix.stackexchange.com/questions/10922/temporarily-suspend-bash-history-on-a-given-shell
