### ISSUE TITLE
Get/View hooks

### ISSUE THREAD

**Issue by davidvader** [go-vela/cli#52]
## Description

Implement hooks management via the Vela CLI

## Value

Offer the same functionality presented in the UI at `/org/repo/hooks` but via the CLI. 
eg.
`vela get hooks --org octocat --repo hello-world`
`vela view hook --org octocat --repo hello-world --hook-number 10`

## Definition of Done

A user can view hooks through the CLI

## Effort  (Optional)

2 days

## Impacted Personas (Optional)

Users

**Comment by jbrockopp** [comment]
Hello 👋

The Vela admins have decided to condense all existing issues into a single repo found @ go-vela/community.

For a direct link to your counterpart issue in that repo, you can find it linked yesterday in the history of this issue.

If you have any questions, please feel free to direct them to the community repo.

Thanks for your input and feedback!
