### ISSUE TITLE
Add the ability to view service logs

### ISSUE THREAD

**Issue by kneal** [go-vela/cli#60]
## Description

_What is your idea?_

The CLI needs the ability to view service logs from a pipeline.

## Value

_Why is this important? Who does it impact? Will this make something better, faster, etc?_

Allows users using services to check their logs via CLI

## Definition of Done

_What is the end goal of this story?_

Logs are viewable

**Comment by annamalai87** [comment]
@kneal Could you assign this issue to me?

**Comment by kneal** [comment]
Gotcha 😄
